services:
  server: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./Untergang/src/
        - action: rebuild
          path: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/Untergang
  db: 
    image: postgres:17.5-alpine
    restart: always
    shm_size: 1024MB
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Untergang
    # Uncomment the section underneath to persist the database
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
